name: Deploy to VPS

on:
  push:
    branches: ["releases"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 1. Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./be_cloudBasedFilePrj
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cloud-backend:latest

      # 2. Build & Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./fe_cloudBasedFilePrj
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cloud-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_KEY }}
          script: |
            # Vào thư mục dự án
            cd cloudBasedFilePrj

            # Pull code mới nhất (chủ yếu để lấy cập nhật nginx hoặc docker-compose)
            git pull

            # Pull Docker Image mới nhất từ Hub về
            docker compose -f docker-compose.prod.yml pull

            # Khởi động lại container
            docker compose -f docker-compose.prod.yml up -d

            # Xóa các image cũ cho đỡ đầy ổ cứng
            docker image prune -f
